name = "French Vanilla"
author = "Ezra Wolf"
version = "1.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f75d4c8145d718c9e3de5a3954b4bf8d422efac64072a9839033aa81b3407071"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
