name = "French Vanilla"
author = "Ezra Wolf"
version = "1.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9dd11743cdb74521c8e468d7c4befd6289ee5c95bd43b63d6ff90d9cccaf2d5"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
