name = "French Vanilla Server"
author = "Ezra Wolf"
version = "1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2bdba7a5fd6747e46c7f2a3c2d662cf2d3eadf78ab380bf0e349c09198e9a16"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
